### ISSUE TITLE
진행사항 점검

### ISSUE THREAD

**Issue by snoopspy** [jungjin0003/Run-Application-as-Root-for-Android#3]
[update]
Update 버튼을 누르면 architecture(64 bit or 32 bit)에 따라 다운받을 zip file name을 결정.
https://github.com/snoopspy/rara/blob/main/architect.cpp

Download가 완료되면 zip 파일을 풀고 적당한 위치(/system/lib, system/lib64)에 관련 파일을 복사.
https://github.com/snoopspy/rara/blob/main/update.cpp

[Root App 선택]
App을 실행하고 나서 특정 App(Activity)을 선택하면 root_app.list에 저장하는 기능 구현 완료.
앱을 실행하고 나서 Android 기기의 /data/data/kr.crazyhacker.rara/files/root_app.list
파일 참고할 것.

혹시 수정 사항 있으면 피드백 주기 바람.

It's time for me to go to bed....

**Comment by jungjin0003** [comment]
코드 확인해봤는데 문제 없는 것 같습니다
